name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0" # Asegúrate de que esta versión del SDK sea compatible

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Agregar esta dependencia para las solicitudes HTTP

  # Paquetes adicionales
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  intl: ^0.19.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Agrega aquí cualquier recurso que utilices en tu aplicación
  assets:
    - assets/images/  # Asegúrate de que esta carpeta existe en tu proyecto si la utilizas

  # Puedes agregar fuentes personalizadas aquí si las usas
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
